### ISSUE TITLE
Incomplete or Deprecated?

### ISSUE THREAD

**Issue by MicBosi** [MicBosi/VisualizationLibrary#102]
**Object Serialization**

VL really needs to be able to serialize/deserialize its classes and data however the current system is quite labor intensive to maintain and we should at least investigate other possibilities. In any case serialization is poorly documented. We should at least ensure a definite subset of VL classes are properly serialized and well documented and allow the user to add de/serialization capability to custom classes.
We might also switch to JSON/BSON rather than our current custom language. It might be more verbose but it would allow better interoperability. We can explicitly declare the data type in JSON by the use of standard suffixes like vertices__f32_ etc. However BSON is only an option if we can store large ints and doubles losslessly and also binary blobs.

**OpenGL ES**

Support for OpenGL ES does not seem to be a priority, we may deprecate and drop altogether its support which is broken anyway, unless someone else helps with its implementation and maintenance.

**Fixed Function Pipeline**

For the future I'm getting more and more convinced that we should drop pre OpenGL 3.2 compatibility and only focus on OpenGL 3.2 onward core compatibility.

**Comment by RallyTronics** [comment]
Have you looked at google's protocol buffer stuff for serialization?

**Comment by MicBosi** [comment]
Thanks looks quite interesting. However one of the requirements for me is to have both a binary and a text format, protocol buffers only support binary. It also tackles only a small part of the problem, the simplest one, reading/writing intermediate representations of objects to/from disk, introducing a bunch of classes and definitions files which need to be kept up to date with VL code and are actually not that useful for us as we still need to then read/create VL objects out of those intermediate representations.

We don't need to create such intermediate objects. Ideally our serialization object would directly read and write VL objects as they are traversing dependencies in the right order, detecting loops, tracking IDs, parent/child relationships, pointers etc. in the process. Which is actually very close to what VLX does now but it's not as complete and robust as I would like it to be.

However I found quite interesting reading about how google protocol buffers handle multiple versions, that's something that the next VL serialization implementation will need need to keep in mind.

**Comment by xnav** [comment]
For what it's worth, protocol buffers can support either binary or text-based representations.  Any protobuf can be represented by a human-readable string that looks somewhat similar to JSON.  The text-based representations are not quite as robust to version changes as the binary ones, but if care is taken with changing "schema" between versions, can be just as good (specifically not eliminating fields that previously existed).  We have developed some library operations to support detection and loading of either binary or text versions, which works well with minimal additional requirements on defining your message schema.  

As the documentation states, protobufs aren't designed for large-object representation, although I have used them with large objects in the past with minimal problem.  The versioning benefits are quite useful.  Written appropriately, data generated in newer versions of a message that is consistent with the expectations of older versions, can be read by "old" code that has no knowledge of the new versions.  The other obvious major benefit is cross-platform ease of use.  It is often nice to be able to easily pull data into another language when working through a bug or development.  Chances are there's a parser in your desired language and you'll instantly be able to use your data.

I do agree with your comment regarding how cumbersome having an intermediate object is; unless you use protocol buffers as your data backing this is indeed an annoyance. 

Note that we haven't used any of the current VL serialization methods; we typically store data in other formats and pass it in.  I'm likely missing a lot of nuance of what is desired and strengths/weaknesses of the current approach.

I got digging around while waiting on this subject while waiting on a lengthy build and stumbled across this http://uscilab.github.io/cereal/.  I'm not sure how mature it is, but it looks more along the lines of what is desired - acting like a boost::serialization but with JSON compatability - and may be a decent starting point.

**Comment by RallyTronics** [comment]
Thanks for posting the Cereal link.  I was going to bring it up but couldn't remember the name.  I have heard a lot of good things about it but haven't worked with it personally.

**Comment by MicBosi** [comment]
Thanks xnav, cereal looks interesting as well.

**Comment by MicBosi** [comment]
Closing with reference to the three separate tickets:
- VLX improvements: https://github.com/MicBosi/VisualizationLibrary/issues/128
- Prioritize glTF: https://github.com/MicBosi/VisualizationLibrary/issues/124
- Legacy OpenGL to be removed: https://github.com/MicBosi/VisualizationLibrary/issues/180, https://github.com/MicBosi/VisualizationLibrary/issues/112
