### ISSUE TITLE
VL tests should use proper argument parser and output and help when no arguments are given

### ISSUE THREAD

**Issue by MicBosi** [MicBosi/VisualizationLibrary#113]
Currently the just crash if you give no arguments which is sad... :'(

**Comment by Fojtik** [comment]
Sorry for duplicity: https://github.com/MicBosi/VisualizationLibrary/issues/164

**Comment by MicBosi** [comment]
@Fojtik ... and only after two more years this is fixed now: https://github.com/MicBosi/VisualizationLibrary/commit/1a7f50e39fc24f9d45830189a287389d4d25db85 😉
