### ISSUE TITLE
Add GLFW support

### ISSUE THREAD

**Issue by totalgee** [MicBosi/VisualizationLibrary#120]
It would be great to have a vlGLFW::GLFWWindow helper class.  Ideally, it should support multiple windows (with the possibility to share contexts) and OpenGL Core Profile, though it would be good to get any GLFW support as a start...

**Comment by RallyTronics** [comment]
how is GLFW better / different from SDL?

**Comment by totalgee** [comment]
GLFW is a simpler/lighter library than SDL, which offers you a lot more
"kitchen sink" features. Personally I prefer not to pull in all kinds of
things I don't need, like networking, threading tools, drawing functions,
CD ROM access, audio and video playback, ... When I need such things I'm
likely to find the cross-platform libraries that best meet my specific
needs. GLFW is also really focused on OpenGL (whereas I believe SDL also
supports the DirectX API, plus has its own 2D drawing functions). I like
the minimalism.

Last time I looked at them (a few years ago), I chose GLFW because it
seemed a more sharply focused tool for my needs (more than sufficient for
window/context creation, event management, device input, etc.). Also, at
the time it was one of the few libraries I found that supported creating
shared OpenGL contexts. (Looks like the latest version of SDL can do this.)
I also find the GLFW documentation on their site very straightforward; it's
easy to find examples of how to set up OpenGL 4+ core profile, work with
Oculus Rift, etc. There was a licensing difference, too, but nowadays
(since SDL 2.0) both libraries use a similar (zlib) license.

SDL is rich and full-featured; it really just depends on what you're
creating! For my particular needs, I found GLFW the more suitable match,
that's all.

Glen.

**Comment by RallyTronics** [comment]
Thanks for the info, I am in the process of choosing which route to take and that was very helpful.  Have you looked at libcinder?  

John

**Comment by totalgee** [comment]
Yes, I really like both Cinder and openFrameworks, but again these are much more complete creative application frameworks that also give you drawing functions, geometric primitives, model/texture loading/saving and much more. In this way, they are more similar to visualizationlibrary than to something like GLFW (although vislib seems to have a different focus, too, and provides tools Cinder and oF don't, such as sophisticated culling, volume visualization, state sorting, LOD).  GLFW is a much smaller, dedicated library just for window/context creation and configuration, input and event management.  (In fact, both openFrameworks and an recent (Vulkan) branch of Cinder **use** GLFW to do handle their cross-platform window/context management).

**Comment by RallyTronics** [comment]
I wrote a GLFW binding for visualization library, are you interested in trying it out?  It does support multiple windows.  I would like someone with more experience with GLFW to take a look at it.

**Comment by MicBosi** [comment]
It'll be added to the next minor release of VL.

**Comment by totalgee** [comment]
Fantastic, thanks!

**Comment by MicBosi** [comment]
Marking this a complete.
