### ISSUE TITLE
Not runing VL on VS 2013 

### ISSUE THREAD

**Issue by AAAAldah** [MicBosi/VisualizationLibrary#125]
I try to run many time using cmake 3.4.1 and the VL and does not give the example file like in the tutorial in main web site and I can't get any example to run .

Thanks

**Comment by MicBosi** [comment]
Please review: http://www.visualizationlibrary.org/documentation/pag_knowledge_base.html

> Note that by default VL applications look for their data in the "../data" subdirectory. If you run the demos make sure you also installed the data by selecting the VL_INSTALL_DATA option from CMake. You can also specify a custom directory using the VL_DATA_PATH environment variable, which is the preferred way usually.

Make sure VL_DATA_PATH is set to something like C:\src\VisualizationLibrary\data from the environment running the examples. 

For general support questions please ask in the user group.
