### ISSUE TITLE
FramebufferObject should be "created" from an already existing FBO (as of OpenGLContext)

### ISSUE THREAD

**Issue by vrince** [MicBosi/VisualizationLibrary#127]
Hi,

In environments where rendering targets are managed deeper (by an other framework) VisualizationLibrary (as a middleware) should be able to instantiate it's own object from existing ressources. 

For example, `FramebufferObject` should have a public constructor taking an already generated / binded fbo, etc ... and not only with `OpenGLContext::createFramebufferObject( ...)`.

This comes in pair with how invasive `InOutContract` classes are in both `vl::Rendering` and `vl::Renderer`. I do think those **must** be optional in environments where opengl state / render targets are supposed (because managed deeper again) to be ready and untouched at `Rendering::render()` time.

I hope this is clear :), I can provide code (PR) for such use case, but I don't hav eany mecanisme yet to restore states once `Rendering::render()` is done

(perhaps name of this issue is not good enough ...)
 
Regards,

**Comment by MicBosi** [comment]
At the moment VL isn't great at cooperating with existing OpenGL contexts. This is definitely the area in which I'd like VL to improve the most in the next major release. I've stumbled in the FBO use case you mention as well, I've ended up using plain OpenGL calls in those cases.

**Comment by MicBosi** [comment]
See issue #88
