### ISSUE TITLE
Vector2/3/4 should get single scalar_type and scalar_type* constructors?

### ISSUE THREAD

**Issue by MicBosi** [MicBosi/VisualizationLibrary#134]
Vector2/3/4 should get single scalar_type and scalar_type\* constructors?

**Comment by RallyTronics** [comment]
This would be great!

**Comment by FabienMathieu** [comment]
Enabling c++11, maybe a constructor getting std::initializer_list could be considered too?

**Comment by MicBosi** [comment]
https://github.com/MicBosi/VisualizationLibrary/commit/3ecb665595a939a36918f978a3bd8ed6e8591ceb
