### ISSUE TITLE
I get build errors with beta 3 when VL_PIPELINE_PRECISION == 2

### ISSUE THREAD

**Issue by RallyTronics** [MicBosi/VisualizationLibrary#147]
Visual Studio 2015...

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2198	'PFNGLUNIFORMMATRIX3FVPROC': too few arguments for call	VLGraphics	F:\VisualizationLibrary_2\src\vlGraphics\ProjViewTransfCallback.cpp	109	
Error	C2440	'type cast': cannot convert from 'vl::mat3' to 'vl::fmat4'	VLGraphics	F:\VisualizationLibrary_2\src\vlGraphics\ProjViewTransfCallback.cpp	109	
Error	C2664	'void vl::Array<vl::fvec3,GLfloat,3,5126>::transform(const vl::mat4 &)': cannot convert argument 1 from 'vl::Matrix4<float>' to 'const vl::mat4 &'	VLGraphics	F:\VisualizationLibrary_2\src\vlGraphics\FlatManipulator.cpp	220	
Error	C2664	'void vl::Array<vl::fvec3,GLfloat,3,5126>::transform(const vl::mat4 &)': cannot convert argument 1 from 'vl::Matrix4<float>' to 'const vl::mat4 &'	VLGraphics	F:\VisualizationLibrary_2\src\vlGraphics\FlatManipulator.cpp	232

**Comment by FabienMathieu** [comment]
Hello, 

I propose a pull request to the main contributor for your issue. Until the pull request be accepted, you can use my branche to solve your problem:

- https://github.com/FabienMathieu/VisualizationLibrary.git

Best regards

Fabien MATHIEU

**Comment by RallyTronics** [comment]
Thanks, I will give it a try tonight when I get home from work.
