### ISSUE TITLE
vlQt5_example - Entry Point Not Found

### ISSUE THREAD

**Issue by mblancomuriel** [MicBosi/VisualizationLibrary#151]
I have successfully followed the steps to for compiling and installing VL in my computer. I am using Visual Studio 14 2015 Win64, Qt 5.8/msvc2015_64 and CMake 3.8.1.  After installing, I go to C:\Program Files\Visualization_Library_SDK\bin. There, when I click twice in vlQt5_example to run the application, I get the following error message: 

> **"The procedure entry point ?getProcAddress@QOpenGLContext@@QEBAP6AXXZPEBD@Z could not be located in the dynamic link library C:\Qt\5.8\msvc2015_64\bin\Qt5OpenGL.dll"**

My computer is a Windows Surface Pro, with Windows 10 Pro, Intel Core i7-6650U @ 2.20 GHz 2.21 GHz. The system type is 64-bit, x64-based processor.

**Comment by MicBosi** [comment]
Doing some issues cleanup. Lmk if the issue is still present.
