### ISSUE TITLE
Camera::adjustView divide by zero error.

### ISSUE THREAD

**Issue by tfiner** [MicBosi/VisualizationLibrary#152]
In the function Camera.cpp(135):
void Camera::adjustView(const AABB& aabb, const vec3& dir, const vec3& up, real bias)

There is a dot product calculated on line 159:
real t = - (R + dot(O,N) - dot(C,N)) / dot(N,V);

Where N is the plane normal, and V is the negative Z modeling matrix vector.
If they are orthogonal (if the user is looking in one of the cardinal directions), then the dot product is 0 and you get a divide by zero error.  Thankfully the VL_CHECK on the line below it fires.

I got this while trying to switch a camera from perspective to orthogonal.

**Comment by MicBosi** [comment]
Thanks @tfiner! I've added a specific check and comment for the divide by zero issue.

https://github.com/MicBosi/VisualizationLibrary/commit/2ebf976ff3c3e9f44bcef26b2912e1398c298c5d
