### ISSUE TITLE
Investigating use of VisualizationLibrary as a rendering library for our physics simulation system. 

### ISSUE THREAD

**Issue by AndySomogyi** [MicBosi/VisualizationLibrary#153]
[Hi](url) @MicBosi , 

We're investigating a number of different graphics backends for our real-time physics similarion syste, and we're looking at VisualizationLibrary. I've got a few questions.

* We support Mac, Windows, and Linux, how good is cross-platform support with VisualizationLibrary?

* How easy is it to hook up VisualizationLibrary to an existing native window, i.e. say on Windows, I create a new Win32 window, or on Mac I create a Cocoa window, is it possible to hook up VisualizationLibrary to that window. I know that I'll have to grab the window events (mouse, resize, etc...) in my app and forward them to VisualizationLibrary, that's not a big deal. We'll be using the native toolkit on each platform for the gui, i.e. WPF on Windows, Cocoa on Mac and GTK on Linux, so it's important that we can hook up our rendering code to native windows.

* Much of our application will entail displaying highly dynamic deformable elastic surfaces and particle systems with programmatically generated textures. Does VisualizationLibrary provide mesh structures where it's easy from the CPU side to change vertex positions / add/remove vertices?

* Does VisualizationLibrary have some kind of scene graph API, that would be great for us, because part of what we'll be doing will be constructive solid geometry, similar to OpenSCAD, http://www.openscad.org, and a scene graph we think is a good way to represent this kind of geometry.

* How open are you to accepting bug fixes/ enhancements, etc. ?

From what I've seen, VisualisationLibrary looks very promising, currently I'm leaning in the direction of VL, or Magnum, [https://github.com/mosra/magnum](url). I like that VL focuses on rendering, provides scene management, and does not try to do everything like physics, audio, etc.

Thanks

**Comment by RallyTronics** [comment]
I am not sure how often he checks this.  You may have better luck in the google group:  https://groups.google.com/forum/#!forum/visualization-library

**Comment by AndySomogyi** [comment]
I tried to join the google group, but admission still pending.

**Comment by RallyTronics** [comment]
You may also want to check out Banshee3D, while it's a gaming engine it is very modular and well documented.  It supports Vulkan as well as opengl and directx https://github.com/BearishSun/BansheeEngine

**Comment by MicBosi** [comment]
Hi @AndySomogyi  hope you had luck for your project. Sorry for not replying here earlier, atm I'm prioritizing other projects. TL;DR; VL can do all you were looking for I think although there is always some learning curve involved. All the best. Mic
