### ISSUE TITLE
Check for null pointer in shutdownGraphics()

### ISSUE THREAD

**Issue by elozanoch** [MicBosi/VisualizationLibrary#161]
The method shutdownGraphics() calls:

defFontManager()->releaseAllFonts();

It think it should first verify if the defFontManager() is not null.

**Comment by MicBosi** [comment]
Thanks @elozanoch! This should no be fixed: https://github.com/MicBosi/VisualizationLibrary/commit/2ebf976ff3c3e9f44bcef26b2912e1398c298c5d
