### ISSUE TITLE
How to build the examples ?

### ISSUE THREAD

**Issue by trlsmax** [MicBosi/VisualizationLibrary#162]
I want to build the glfw examples , in the cmake gui, the option VL_GUI_GLFW_EXAMPLES is enabled. But after the make command, I can't find the compiled examples.

**Comment by yslib** [comment]
The option in examples folder's CMakeLists.txt is VL_GUI_GLEW_EXAMPLES rather than VL_GUI_GLFW_EXAMPLES. You could fix it by yourself.

**Comment by trlsmax** [comment]
Thank you. It works now.
