### ISSUE TITLE
Compiling VL library with wxWidgets support

### ISSUE THREAD

**Issue by PierSimonTilma** [MicBosi/VisualizationLibrary#165]
I am trying to compile the Visualization Library. Everything goes well except when I want
to add wxWidgets support. Generating makefiles with CMake works okay. Paths to the
wxWidgets libraries are correct. 

The first error displayed is :
WXGLCanvas.cpp:76:66: error: no matching function for call to 'wxGLCanvas::wxGLCanvas(wxWindow*&, const wxGLContext*&, wxWindowID&, const wxPoint&, const wxSize&, long int&, const wxString&, int*&)' wxGLCanvas(parent, shared, id, pos, size, style, name, attribList)

Used library : wxWidgets 3.1.1
Compiler : MingW GCC 4.8.3

Pier Tilma, 20-10-2018, The Netherlands

**Comment by asmwarrior** [comment]
I meet the same issue here.
wxWidgets 3.1+ library, the wxGLCanvas constructor has changed the function prototype, see here:
[wxWidgets/glcanvas.h at master · wxWidgets/wxWidgets](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/msw/glcanvas.h)
So, I think the WXGLCanvas.cpp/h should be adjusted. Especially, we should follow the sample code in [pyramid.cpp](https://github.com/wxWidgets/wxWidgets/blob/master/samples/opengl/pyramid/pyramid.cpp).

I have tried several hours, but still failed to get the modified code build successfully.

**Comment by MicBosi** [comment]
@PierSimonTilma @asmwarrior Atm VL only supports wxWidgets 2.8, not 3.x. If you'd like to contribute you could create a 3.x binding modeled after the 2.8 one and send over a PR.
