### ISSUE TITLE
The option in examples folder's CMakeLists.txt is VL_GUI_GLEW_EXAMPLES rather than VL_GUI_GLFW_EXAMPLES. 

### ISSUE THREAD

**Issue by yslib** [MicBosi/VisualizationLibrary#166]
It will causes that examples part won't be configured and compiled.

**Comment by MicBosi** [comment]
Thanks @yslib! This should no be fixed: https://github.com/MicBosi/VisualizationLibrary/commit/2ebf976ff3c3e9f44bcef26b2912e1398c298c5d
