### ISSUE TITLE
lowercase 'd' in include statements for Defines.hpp

### ISSUE THREAD

**Issue by istlota** [MicBosi/VisualizationLibrary#170]
I downloaded the code using Qt Creator's git client, but build failed due to include statements for Defines.hpp being coded with a lowercase 'd' in three files: ParserVLT.hpp. ParserVLB.hpp, and WrappersCore.hpp.

**Comment by MicBosi** [comment]
Thanks @istlota! This should no be fixed: https://github.com/MicBosi/VisualizationLibrary/commit/2ebf976ff3c3e9f44bcef26b2912e1398c298c5d
