### ISSUE TITLE
Update Support to wxWidgets 2.x and 3.x

### ISSUE THREAD

**Issue by MicBosi** [MicBosi/VisualizationLibrary#172]
Support for wxWidgets 2.8 is now becoming obsolete. Would be nice to support 3.x as well. Contributions are welcome.

https://www.wxwidgets.org/downloads/

**Comment by MicBosi** [comment]
Related: https://github.com/MicBosi/VisualizationLibrary/issues/114

**Comment by VirgiliuC** [comment]
Hi Mic

Attached please find the vlWX Canvas zipped source files for wxWidgets 3.x.

Here is an example from our applications on how to use it:
```
...
#ifdef WXMSW_3.1

    wxGLAttributes glAttribs;
    wxGLContextAttrs contextAttribs;

    glAttribs.RGBA().Depth(24).DoubleBuffer().SampleBuffers(1).Samplers(8).EndList();

    if(use_OpenGL_Debug)
        contextAttribs.CompatibilityProfile().DebugCtx().EndList();
    else
        contextAttribs.CompatibilityProfile().OGLVersion(3,3).EndList();

    contextAttribs.SetNeedsARB(true);

//Create the canvas.
    mCanvas = new vlWX::WXGLCanvas(panGraphicsHost, NULL, wxID_ANY,
                                   panGraphicsHost->GetClientAreaOrigin(),
                                   panGraphicsHost->GetClientSize(),
                                   wxFULL_REPAINT_ON_RESIZE,
                                   &glAttribs, &contextAttribs);

#else // WXMSW < 3.1
...
```
where _panGraphicsHost_ is a simple _wxPanel_ hosting the VL canvas (the rendering surface).

We've been using VL + WX 3.x for quite a long while now and they work absolutely fine together.
Hope that helps.

Regards,
Virgiliu

[vlWX.zip](https://github.com/MicBosi/VisualizationLibrary/files/4191985/vlWX.zip)

**Comment by MicBosi** [comment]
Hey! 😃 Thanks @VirgiliuC!

**Comment by MicBosi** [comment]
Closing: https://github.com/MicBosi/VisualizationLibrary/commit/3fa9a8f68bed991fe53c19e8beb012171c4b2434
